index:
    path: /
    controller: App\Controller\DefaultController::index
inventory-add:
    path: /inventory-add
    controller: App\Controller\InventoryController::addInventory
inventory-update:
    path: /inventory-update
    controller: App\Controller\InventoryController::updateInventory
item-add:
    path: /item-add
    controller: App\Controller\ItemController::addItem
item-update:
    path: /item-update
    controller: App\Controller\ItemController::updateItem